import path from 'path';
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://samur-ai-gules.vercel.app/');
  await page.getByRole('banner').getByRole('button').click();
  await page.getByRole('button', { name: 'Join as a School HR' }).click();
  await page.getByRole('textbox', { name: 'Enter School Name' }).click();
  await page.getByRole('textbox', { name: 'Enter School Name' }).fill('APSACS');
  await page.getByRole('textbox', { name: 'Enter your name' }).click();
  await page.getByRole('textbox', { name: 'Enter your name' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Enter your name' }).fill('Steve Smith');
  await page.getByRole('textbox', { name: 'Enter email address' }).click();
  await page.getByRole('textbox', { name: 'Enter email address' }).fill('steve.hrmanager@yopmail.com');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('+974 3554 2200');
  await page.locator('div').filter({ hasText: /^Select your region$/ }).nth(3).click();
  await page.getByRole('option', { name: 'Al Daayen' }).click();
  await page.locator('.DropdownOptionContainer.undefined__input-container').click();
  await page.getByRole('option', { name: 'Al Wakrah' }).click();
  await page.getByRole('textbox', { name: 'Enter address here' }).click();
  await page.getByRole('textbox', { name: 'Enter address here' }).fill('Testing description');
  await page.getByRole('textbox', { name: 'Enter notes here' }).dblclick();
  await page.getByRole('textbox', { name: 'Enter notes here' }).fill('None');
  await page.getByRole('button', { name: 'Submit' }).click();
  // await page.goto('https://admin.samuraiinnovations.com/');
  // await page.getByRole('textbox', { name: 'doe.john@gmail.com' }).click();
  // await page.getByRole('textbox', { name: 'doe.john@gmail.com' }).fill('shadi.azzam@samuraiinnovations.com');
  // await page.getByRole('textbox', { name: '**********' }).click();
  // await page.getByRole('textbox', { name: '**********' }).fill('Call@911');
  // await page.getByRole('button', { name: 'Login to Admin' }).click();
  // await page.getByRole('heading', { name: 'Welcome, Admin' }).getByRole('img').click();
  // await page.getByRole('link', { name: 'School Intake List' }).click();
  // await page.getByRole('row', { name: 'APSACS Steve Smith +' }).getByRole('button').click();
  // await page.locator('.DropdownOptionContainer.undefined__input-container').click();
  // await page.getByRole('option', { name: 'Al Shamal' }).click();
  // const pdfPath = path.resolve("D:\\Rana Samiuddin\\Automation\\Software Testing Strategies.pdf");
  // await page.locator('input[type="file"]').setInputFiles(pdfPath);
  // await page.getByRole('button', { name: 'Submit' }).click();
});